### ISSUE TITLE
Timeout for Read in initAntDevice

### ISSUE THREAD

**Issue by mado89** [glever/j-antplus#11]
Hi,

first of all thanks for creating this library! I am trying to get it running on my machine to check whether I can use it for my project. I tried running the "HrmTest_Main" example. But it seems there is either a problem with my specific ant stick or a problem with the library?

I had to divert from the instructions as my ant stick does not have the product id 1009 but 1008. Also, I had to change the vendor from fcf to "0fcf". But I am not sure if this is causing the problems. Can you detect something from the output below?

```
D/12-26 17:38:14 596  [AntUsbReader] Read A4-01-6F-20-EA-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 bytes
D/12-26 17:38:14 710  [AntMessageRegistry] Converted A4-01-6F-20-EA to StartupNotificationMessage
E/12-26 17:38:14 922  [AntUsbWriter] Sending ResetSystemMessage with bytes A4-01-4A-00-EF-00-00.
D/12-26 17:38:14 934  [AntUsbReader] Read A4-01-6F-20-EA-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 bytes
D/12-26 17:38:14 935  [AntMessageRegistry] Converted A4-01-6F-20-EA to StartupNotificationMessage
E/12-26 17:38:15 531  [AntUsbWriter] Sending RequestMessage with bytes A4-04-4D-00-54-00-00-B9-00-00.
D/12-26 17:38:15 560  [AntUsbReader] Read A4-06-54-08-03-00-BA-36-00-71-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 bytes
E/12-26 17:38:15 598  [AntUsbReader] Fatal error reading from usb device Incorrect message length. Given: 6, expected: 8
E/12-26 17:38:26 047  [AntUsbWriter] Sending ResetSystemMessage with bytes A4-01-4A-00-EF-00-00.
Exception in thread "main" be.glever.ant.AntException: java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
	at be.glever.ant.usb.AntUsbDevice.initialize(AntUsbDevice.java:89)
	at be.glever.anttest.HrmTest_Main.<init>(HrmTest_Main.java:26)
	at be.glever.anttest.HrmTest_Main.main(HrmTest_Main.java:35)
Caused by: java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Flux.blockFirst(Flux.java:2488)
	at be.glever.ant.usb.AntUsbDevice.sendBlocking(AntUsbDevice.java:203)
	at be.glever.ant.usb.AntUsbDevice.initAntDevice(AntUsbDevice.java:270)
	at be.glever.ant.usb.AntUsbDevice.initialize(AntUsbDevice.java:86)
	... 2 more

Process finished with exit code 1
```

Thanks for your help!

**Comment by glever** [comment]
Hi mado89,

I'm afraid to say I'm no longer working on this library since a long time, basically this repo has become abandonware, sorry.
Perhaps check the documentation on the hrm models, I believe there is a mention of older device types that require different messages.

I feel a bit guilty that I cannot respond to questions of other developers, I'm thinking of either removing this repo or disabling the issue system.

**Comment by mado89** [comment]
Hi glever,

thanks for your answer anyway. I think I found a workaround for this: The ant+ stick I am using sends fewer bytes somewhere. I will check this and maybe create a pull request for it.

I think there is a "Deprecated" or "Abandoned" setting somewhere which you can use for your repo.

**Comment by Cypri1998** [comment]
HI, I have the same errors, have you successfully corrected this problem?
Thx !
