### ISSUE TITLE
Ant Exception

### ISSUE THREAD

**Issue by Cypri1998** [glever/j-antplus#13]
Hi !
Firstly sorry for my english, i'm a French student and I have an issue...

When I run the HrmTest_Main,, I have the Issue that you can find on my picture.
I don't know how to solve it... 
Is-there someone who encounter that?
 
Thanks a lot!

**Comment by Cypri1998** [comment]
![Uploading Issue HrmTest_Main.png…]()
This one eheh

**Comment by Cypri1998** [comment]
Or here 👍

-----------
Exception in thread "main" java.lang.NoClassDefFoundError: be/glever/ant/AntException
	at be.glever.anttest.HrmTest_Main.<init>(HrmTest_Main.java:25)
	at be.glever.anttest.HrmTest_Main.main(HrmTest_Main.java:36)
Caused by: java.lang.ClassNotFoundException: be.glever.ant.AntException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
----------

I don't understand this error
